# Generated by Django 4.0.6 on 2022-09-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='product_guide/documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Металл')),
            ],
            options={
                'verbose_name': 'Металл',
                'verbose_name_plural': 'Металлы',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Полное наименование поставщика')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('checking_account', models.IntegerField(blank=True, null=True, verbose_name='Рассчетный сет')),
                ('bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк')),
                ('bik', models.IntegerField(blank=True, null=True, verbose_name='БИК')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Грузополучатель',
                'verbose_name_plural': 'Грузополучатели',
            },
        ),
        migrations.AlterModelOptions(
            name='jewelry',
            options={'ordering': ['metal', 'name', '-weight'], 'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AddField(
            model_name='jewelry',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прихода'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='price_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Цена за грамм'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='trademark',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Торговая марка'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='coating',
            field=models.CharField(blank=True, choices=[('Чернение', 'Чернение'), ('Золочение', 'Золочение'), ('Родирование', 'Родирование'), ('Оксидирование', 'Оксидирование')], max_length=20, null=True, verbose_name='Покрытие'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_reg_status',
            field=models.CharField(choices=[('Зарегистрирован', 'Зарегистрирован'), ('Не зарегистрирован', 'Не зарегистрирован')], max_length=50, verbose_name='Статус регистрации в ГИИС'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_status',
            field=models.CharField(blank=True, choices=[('Числится на хранении', 'Числится на хранении'), ('Выбыл из ГИИС', 'Выбыл из ГИИС')], max_length=20, null=True, verbose_name='Статус ГИИС'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Артикул'),
        ),
        migrations.CreateModel(
            name='OutgoingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True, verbose_name='Номер накладной')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.provider', verbose_name='Поставщик')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.recipient', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Исходящая накладная',
                'verbose_name_plural': 'Исходящие накладные',
            },
        ),
        migrations.CreateModel(
            name='InputInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True, verbose_name='Номер накладной')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Дата прихода')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.provider', verbose_name='Поставщик')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.recipient', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Входящая накладная',
                'verbose_name_plural': 'Входящие накладные',
            },
        ),
        migrations.AddField(
            model_name='jewelry',
            name='input_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.inputinvoice', verbose_name='Входящая накладная'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='outgoing_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.outgoinginvoice', verbose_name='Исходящая накладная'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_guide.metal', verbose_name='Металл'),
        ),
    ]
