# Generated by Django 4.0.6 on 2022-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'ordering': ['metal', 'name', '-weight'], 'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_reg_status',
            field=models.CharField(choices=[('yes', 'Зарегистрирован в ГИИС'), ('no', 'Не зарегистрирован в ГИИС')], max_length=50, verbose_name='Статус регистрации в ГИИС'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_status',
            field=models.CharField(choices=[('listed', 'Числится на хранении'), ('dropped_out', 'Выбыл из ГИИС')], max_length=20, null=True, verbose_name='Статус ГИИС'),
        ),
    ]
