# Generated by Django 4.0.6 on 2022-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0002_metal_provider_recipient_alter_jewelry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='product_guide/documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
