# Generated by Django 4.0.6 on 2022-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0002_alter_jewelry_options_alter_jewelry_giis_reg_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='coating',
            field=models.CharField(blank=True, choices=[('Чернение', 'Чернение'), ('Золочение', 'Золочение'), ('Родирование', 'Родирование'), ('Оксидирование', 'Оксидирование')], max_length=20, null=True, verbose_name='Покрытие'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_reg_status',
            field=models.CharField(choices=[('Зарегистрирован', 'Зарегистрирован'), ('Не зарегистрирован', 'Не зарегистрирован')], max_length=50, verbose_name='Статус регистрации в ГИИС'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_status',
            field=models.CharField(blank=True, choices=[('Числится на хранении', 'Числится на хранении'), ('Выбыл из ГИИС', 'Выбыл из ГИИС')], max_length=20, null=True, verbose_name='Статус ГИИС'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='metal',
            field=models.CharField(choices=[('Золото 585', 'Золото 585'), ('Серебро 925', 'Серебро 925')], max_length=11, verbose_name='Металл'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Артикул'),
        ),
    ]
