# Generated by Django 4.0.6 on 2022-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0003_alter_jewelry_metal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputinvoice',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Накладная'),
        ),
        migrations.AddField(
            model_name='outgoinginvoice',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Накладная'),
        ),
    ]
