# Generated by Django 4.0.6 on 2022-09-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
