# Generated by Django 4.0.6 on 2022-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0004_inputinvoice_title_outgoinginvoice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес'),
        ),
    ]
