# Generated by Django 4.0.6 on 2022-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0005_file_date_time_of_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
