# Generated by Django 4.0.6 on 2022-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0005_alter_jewelry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price_per_gram',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за грамм'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
