# Generated by Django 4.0.6 on 2022-10-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0006_alter_jewelry_price_alter_jewelry_price_per_gram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoice',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата прихода'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата прихода'),
        ),
        migrations.AlterField(
            model_name='outgoinginvoice',
            name='departure_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
