# Generated by Django 4.0.6 on 2022-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0007_alter_inputinvoice_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='giis_reg_status',
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='giis_status',
            field=models.CharField(blank=True, choices=[('На хранении', 'На хранении'), ('Выбыл', 'Выбыл')], max_length=20, null=True, verbose_name='Статус ГИИС'),
        ),
    ]
