# Generated by Django 4.0.6 on 2022-10-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0008_remove_jewelry_giis_reg_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='price_per_gram',
        ),
    ]
