# Generated by Django 4.0.6 on 2022-10-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0009_remove_jewelry_price_per_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.recipient', verbose_name='Получатель'),
        ),
    ]
