# Generated by Django 4.0.6 on 2022-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0010_jewelry_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='tel',
        ),
        migrations.AddField(
            model_name='recipient',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Получатель'),
        ),
    ]
