# Generated by Django 4.0.6 on 2022-10-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0011_remove_recipient_address_remove_recipient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Полное наименование поставщика')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('checking_account', models.IntegerField(blank=True, null=True, verbose_name='Рассчетный сет')),
                ('bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк')),
                ('bik', models.IntegerField(blank=True, null=True, verbose_name='БИК')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='checking_account',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='tel',
        ),
        migrations.AddField(
            model_name='provider',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Поставщик'),
        ),
    ]
