# Generated by Django 4.0.6 on 2022-10-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0015_remove_inputinvoice_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparties',
            options={'verbose_name': 'Контрагента', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='inputinvoice',
            options={'verbose_name': 'Входящую накладную', 'verbose_name_plural': 'Входящие накладные'},
        ),
        migrations.AlterModelOptions(
            name='outgoinginvoice',
            options={'verbose_name': 'Исходящую накладную', 'verbose_name_plural': 'Исходящие накладные'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Поставщика', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Грузополучателя', 'verbose_name_plural': 'Грузополучатели'},
        ),
        migrations.RenameField(
            model_name='jewelry',
            old_name='input_invoice_id',
            new_name='input_invoice',
        ),
        migrations.RenameField(
            model_name='jewelry',
            old_name='outgoing_invoice_id',
            new_name='outgoing_invoice',
        ),
        migrations.RenameField(
            model_name='jewelry',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='jewelry',
            old_name='recipient_id',
            new_name='recipient',
        ),
    ]
