# Generated by Django 4.0.6 on 2022-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0016_alter_counterparties_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedModelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
