# Generated by Django 4.0.6 on 2022-11-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0017_extendedmodelsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedModelsModel',
        ),
    ]
