# Generated by Django 4.0.6 on 2022-11-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0018_delete_extendedmodelsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='trademark',
        ),
    ]
