# Generated by Django 4.0.6 on 2022-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0021_alter_jewelry_options_provider_counterparties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='giis_status',
            field=models.CharField(blank=True, choices=[('Хранение', 'Хранение'), ('Выведено', 'Выведено')], max_length=20, null=True, verbose_name='Статус ГИИС'),
        ),
    ]
