# Generated by Django 4.0.6 on 2022-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0022_alter_jewelry_giis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='giis_status',
            field=models.CharField(blank=True, choices=[('На хранении', 'На хранении'), ('Выведено', 'Выведено')], max_length=20, null=True, verbose_name='Статус ГИИС'),
        ),
    ]
