# Generated by Django 4.0.6 on 2022-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0023_alter_jewelry_giis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Полное наименование поставщика'),
        ),
    ]
