# Generated by Django 4.0.6 on 2022-11-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0024_alter_counterparties_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='checking_account',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рассчетный счет'),
        ),
    ]
