# Generated by Django 4.0.6 on 2022-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0025_alter_counterparties_checking_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='price',
        ),
        migrations.AddField(
            model_name='jewelry',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='selling_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Отпускная цена'),
        ),
    ]
