# Generated by Django 4.0.6 on 2022-12-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0026_remove_jewelry_price_jewelry_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='counterparties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.counterparties', verbose_name='Контрагент'),
        ),
    ]
