# Generated by Django 4.0.6 on 2022-12-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0027_recipient_counterparties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoice',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='recipient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.recipient', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='outgoinginvoice',
            name='recipient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.recipient', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='counterparties',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.counterparties', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='counterparties',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_guide.counterparties', verbose_name='Контрагент'),
        ),
    ]
