# Generated by Django 4.0.6 on 2022-12-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0028_alter_inputinvoice_provider_alter_jewelry_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='departure_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
