# Generated by Django 4.0.6 on 2022-12-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0029_jewelry_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='availability_status',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Продано', 'Продано'), ('Передано', 'Передано'), ('Передано по договору', 'Передано по договору')], max_length=50, verbose_name='Статус наличия'),
        ),
    ]
