# Generated by Django 4.0.6 on 2022-12-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0030_alter_jewelry_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparties',
            name='passport_info',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Информация о выдаче пасспорта'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
