# Generated by Django 4.0.6 on 2022-12-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0031_counterparties_passport_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='passport_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Информация о выдаче паспорта'),
        ),
    ]
