# Generated by Django 4.0.6 on 2022-12-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0032_alter_counterparties_passport_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoinginvoice',
            options={'ordering': ['invoice_number'], 'verbose_name': 'Исходящую накладную', 'verbose_name_plural': 'Исходящие накладные'},
        ),
        migrations.AddField(
            model_name='jewelry',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснения'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул'),
        ),
    ]
