# Generated by Django 4.0.6 on 2023-01-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0033_alter_outgoinginvoice_options_jewelry_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputInvoice',
            new_name='IncomingInvoice',
        ),
    ]
