# Generated by Django 4.0.6 on 2023-01-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0034_rename_inputinvoice_incominginvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incominginvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='outgoinginvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер накладной'),
        ),
    ]
