# Generated by Django 4.0.6 on 2023-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_guide', '0035_alter_incominginvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='purchase_price_per_gram',
            field=models.FloatField(blank=True, null=True, verbose_name='Закуп за грамм'),
        ),
    ]
